spring.application.name=JobPortal

spring.datasource.url=jdbc:mysql://localhost:3306/jobportal
spring.datasource.username=root
spring.datasource.password=123Prasanna@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

twilio.account.sid=AC64dd853c4a7ea4ecddec0d4a1c4a8365
twilio.auth.token=c6a543add6700c648cd0dc5d36224cb4
twilio.phone.number=+16162084891

